CREATE TABLE [dbo].[tblDocArchive](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[TheNumber] [bigint] NOT NULL,
	[FileName] [nvarchar](25) NOT NULL,
	[FilePath] [nvarchar](400) NOT NULL,
	[Notes] [nvarchar](250) NULL,
	[UserID] [bigint] DEFAULT ((1)),
	[BranchID] [bigint] NOT NULL,
	[EnterTime] [datetime] DEFAULT (getdate()),
	[IdCard] [nvarchar](250) NULL,
	[DocType] [int] DEFAULT ((1)),
	[TheYear] [smallint] NOT NULL,
 CONSTRAINT [PK_tblDocArchiveDetails] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ_TheNumber_PerBranch] UNIQUE NONCLUSTERED 
(
	[TheNumber] ASC,
	[BranchID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]


CREATE TABLE [dbo].[tblBranches](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[TheNumber] [bigint] NOT NULL,
	[BranchName] [varchar](50) NOT NULL,
	[Notes] [varchar](250) NULL,
	[EnterTime] [datetime] DEFAULT getdate()
 CONSTRAINT [PK_tblBranches] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [IX_tblBranches] UNIQUE NONCLUSTERED 
(
	[TheNumber] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [IX_tblBranches_BranchName] UNIQUE NONCLUSTERED 
(
	[BranchName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO